### PR TITLE
Bump to 1.8.1rc1

### PR DESCRIPTION
**Pull request by tomvothecoder**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tomvothecoder** [comment]
@conda-forge-admin, please rerender

**Comment by tomvothecoder** [comment]
Hi @xylar, I went ahead and bumped the version of `e3sm_to_cmip` to `v1.8.1rc1`. 

This is my first time bumping a version in a conda-forge feedstock. It was pretty straightforward, but let me know if I'm missing anything.

**Comment by xylar** [comment]
@tomvothecoder, this would need to go to the `dev`, not the `master` branch.  Could you edit that?  And we would need to add a file identical to this one:
https://github.com/conda-forge/e3sm_diags-feedstock/blob/dev/recipe/conda_build_config.yaml

Other than that, this looks good.

**Comment by xylar** [comment]
After you add those changes, we will need to ask the bot to rerender before we merge.

**Comment by tomvothecoder** [comment]
@conda-forge-admin, please rerender

**Comment by tomvothecoder** [comment]
Thanks @xylar, I now see the connection between the `dev` branch and releases with the conda-forge `e3sm_dev` label. I've swapped the root branch to `dev`, and added `conda_build_config.yaml`.

Note, this branch started out from `master`, so it pulled in the latest changes from there. You'll notice a larger diff, but this seems fine to me. Let me know otherwise.

**Comment by xylar** [comment]
Sorry, I'll take care of updating `dev` first, then I'll merge this.  Thanks for the work, @tomvothecoder!

**Pull request merged**
